version: '3'
services:
  postgres:
    image: postgres:13
    restart: always
    environment:
      POSTGRES_USER: nakama
      POSTGRES_PASSWORD: password
      POSTGRES_DB: nakama
    ports:
      - "5432:5432"

  nakama:
    image: heroiclabs/nakama:3.13.0
    depends_on:
      - postgres
    environment:
      NAKAMA_DATABASE__ADDRESS: "postgres:5432"
      NAKAMA_DATABASE__USER: "nakama"
      NAKAMA_DATABASE__PASSWORD: "password"
      NAKAMA_DATABASE__NAME: "nakama"
    ports:
      - "7350:7350"
      - "7349:7349"
    volumes:
      - ./modules:/nakama/data/modules
